package com.example.presentation.onboarding

const val LEGAL_DOCUMENTATION_TEXT = """YANTRA
Your Phone Is Your Lab

Legal Documentation Package
Terms of Service · EULA · Privacy Policy · Disclaimer
Effective Date: 1 June 2026

This document package contains all legal agreements governing the use of the Yantra mobile application. By downloading, installing, or using Yantra in any way, you agree to be bound by all documents contained herein. Please read everything carefully before use.

Document
	Contents
	Terms of Service
	Governs your use of the Yantra app, your rights and responsibilities, and the limits of our liability.
	End User License Agreement (EULA)
	Governs your license to use the Yantra software. Covers intellectual property, restrictions on use, and termination.
	Privacy Policy
	Explains exactly what data Yantra collects (almost none), where it lives, and your rights over it.
	Scientific Accuracy Disclaimer
	Explains the limitations of phone-sensor-based experiments and what the data can and cannot be used for.
	Minor User Policy
	Governs use of Yantra by users under 18, including parental consent requirements.
	________________

DOCUMENT 1 — TERMS OF SERVICE
Effective Date: 1 June 2026

BY DOWNLOADING, INSTALLING, OR USING YANTRA, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO THESE TERMS OF SERVICE IN THEIR ENTIRETY. IF YOU DO NOT AGREE, DO NOT USE THE APP.

1. Who We Are
Yantra is a science experiment application developed and maintained by Raghav Gangrade (operating as "Yantra Labs"), an independent software project based in Barwani, Madhya Pradesh, India. References to "Yantra", "we", "us", or "our" throughout this document refer to Yantra Labs. References to "you", "your", or "user" refer to any individual who downloads, installs, accesses, or uses the Yantra application.
2. What Yantra Is
Yantra is an educational mobile application that uses the built-in sensors of Android smartphones to facilitate science experiments mapped to the Indian school curriculum (CBSE and select state boards). Yantra generates experimental data based on sensor readings and produces formatted lab reports from that data.

Yantra is:
* An educational tool for personal and academic learning
* A sensor data collection and analysis application
* A lab report generation tool for student use

Yantra is NOT:
* A certified scientific instrument or measurement device
* A replacement for professional laboratory equipment
* A source of data for use in professional, commercial, medical, engineering, or legal contexts
* A platform for sharing data or communicating with other users
3. Acceptance of Terms
By taking any of the following actions, you are entering into a legally binding agreement with Yantra Labs and accepting these Terms of Service:
1. Downloading the Yantra application from any source
2. Installing the Yantra application on any device
3. Opening or launching the Yantra application
4. Using any feature of the Yantra application
5. Allowing any other person to use the Yantra application on your device

If you are a minor (under 18 years of age), your parent or legal guardian must read and accept these Terms on your behalf. By allowing a minor to use Yantra, the parent or guardian accepts these Terms and takes full responsibility for the minor's use of the application.
4. License to Use
Subject to your compliance with these Terms, Yantra Labs grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to install and use the Yantra application on a single Android device that you own or control, solely for your personal, non-commercial, educational purposes.

This license does not permit you to:
* Copy, reproduce, or distribute the Yantra application or any part of it
* Modify, adapt, translate, reverse engineer, decompile, or disassemble the application
* Create derivative works based on the application
* Remove or alter any proprietary notices, labels, or marks
* Use the application for any commercial purpose or for any public display
* Transfer the application or this license to any other person
* Use the application on more than one device simultaneously without explicit written permission
5. Permitted Use
Yantra is designed for use by students enrolled in Indian secondary school programmes (Classes 9 through 12). You may use Yantra to:
* Conduct science experiments using your smartphone sensors
* Collect and analyse experimental data for personal educational purposes
* Generate lab reports for submission to your school or teacher
* Track your experimental progress for personal reference

Lab reports generated by Yantra may be submitted to your school as part of your practical file, provided that the data contained in the report was genuinely collected by you using the Yantra application during an actual experiment performed by you.
6. Prohibited Conduct
You must not use Yantra in any of the following ways:
* To produce false, fabricated, or misleading experimental data or lab reports
* To submit lab reports as your own work when the underlying experiment was not performed by you
* To attempt to access, modify, or interfere with any part of the application's code, data, or functionality
* To use the application in any way that violates applicable law
* To use the application for any purpose other than personal educational use
* To attempt to extract, scrape, or copy the experiment content, instructions, or templates from the application
* To use the application in contexts where inaccurate sensor data could cause harm (see Section 8)
7. Intellectual Property
All content within the Yantra application — including but not limited to experiment instructions, calculation methods, report templates, user interface design, text, graphics, code, and the application itself — is the exclusive intellectual property of Yantra Labs and is protected under applicable Indian and international intellectual property laws.

Nothing in these Terms grants you any ownership of or rights in the intellectual property of Yantra Labs. The data that your phone sensors produce during your experiments belongs to you. The templates, calculations, and report formats that Yantra uses to process and present that data belong to Yantra Labs.
8. Accuracy Disclaimer and Limitation of Use
Yantra uses consumer-grade smartphone sensors to collect experimental data. These sensors are not precision scientific instruments. The data they produce is subject to measurement error, device variation, calibration drift, environmental interference, and physical limitations. Yantra processes this data and presents results that are useful for educational purposes but are approximations, not precise measurements.

YOU MUST NOT USE DATA OR RESULTS GENERATED BY YANTRA FOR ANY PURPOSE OUTSIDE OF PERSONAL EDUCATIONAL USE. THIS INCLUDES BUT IS NOT LIMITED TO: MEDICAL DECISIONS, ENGINEERING CALCULATIONS, STRUCTURAL ANALYSIS, SAFETY DETERMINATIONS, LEGAL OR REGULATORY SUBMISSIONS, OR ANY PROFESSIONAL OR COMMERCIAL APPLICATION.

Any reliance on Yantra data for purposes beyond personal educational learning is entirely at your own risk. Yantra Labs expressly disclaims all liability for any harm, loss, or damage arising from such reliance.
9. Device and Safety
PHYSICAL EXPERIMENT LIABILITY: Yantra instructs users to perform physical experiments using their devices. Users assume ALL risk associated with these activities. Yantra Labs and its developers are NOT liable for any physical damage to devices, property, or persons resulting from the setup or execution of these experiments (including, but not limited to, dropping, swinging, or impacting the device).
Certain experiments in Yantra require you to handle your phone in ways that carry a risk of physical damage to your device, including dropping it. Yantra provides explicit warnings before any such experiment. You acknowledge and accept that:
* You perform all experiments entirely at your own risk
* Yantra Labs is not responsible for any damage to your device caused by performing experiments
* You should read all warnings and setup instructions carefully before beginning any experiment
* You should ensure your physical environment is safe before performing any experiment
* You should not perform experiments in unsafe environments or conditions
10. No Warranty
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YANTRA AND ALL CONTENT, DATA, AND SERVICES PROVIDED THROUGH IT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.

YANTRA LABS EXPRESSLY DISCLAIMS ALL WARRANTIES INCLUDING BUT NOT LIMITED TO: WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, RELIABILITY, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.

YANTRA LABS DOES NOT WARRANT THAT THE APPLICATION WILL BE ERROR-FREE, UNINTERRUPTED, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
11. Limitation of Liability
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YANTRA LABS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF OR RELATING TO YOUR USE OF OR INABILITY TO USE YANTRA, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF DEVICE FUNCTIONALITY, ACADEMIC CONSEQUENCES, OR ANY OTHER DAMAGES.

IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CERTAIN DAMAGES, YANTRA LABS'S LIABILITY IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.

BECAUSE YANTRA IS PROVIDED FREE OF CHARGE, THE TOTAL LIABILITY OF YANTRA LABS TO YOU FOR ANY CLAIMS ARISING FROM YOUR USE OF THE APP SHALL NOT EXCEED ZERO RUPEES (INR 0). YOU ACKNOWLEDGE THAT THIS REFLECTS A REASONABLE ALLOCATION OF RISK GIVEN THE FREE NATURE OF THE SERVICE.
12. Indemnification
You agree to indemnify, defend, and hold harmless Yantra Labs and its developers, contributors, officers, and representatives from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to:
* Your use or misuse of the Yantra application
* Your violation of these Terms of Service
* Your violation of any applicable law or regulation
* Any claim that your use of Yantra caused damage to a third party
* The submission of fraudulent or fabricated experimental data or lab reports
13. Modifications to Terms
Yantra Labs reserves the right to modify these Terms of Service at any time. When modifications are made, the updated Terms will be made available within the application. The effective date at the top of this document will be updated to reflect the date of the most recent revision.

Your continued use of Yantra after the effective date of any modification constitutes your acceptance of the modified Terms. If you do not agree with any modification, you must stop using the application immediately.
14. Termination
Yantra Labs reserves the right to terminate or suspend your license to use the application immediately and without notice if you breach any provision of these Terms. Upon termination, you must cease all use of the application and delete it from your device. All data stored locally on your device will remain on your device — Yantra Labs has no ability to access or delete it remotely.

You may terminate your use of Yantra at any time by uninstalling the application. Uninstalling the application terminates this agreement, though provisions that by their nature should survive termination — including intellectual property, disclaimer of warranties, limitation of liability, and indemnification — shall survive.
15. Governing Law and Jurisdiction
These Terms of Service shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any dispute, claim, or controversy arising out of or relating to these Terms, the Yantra application, or your use thereof shall be subject to the EXCLUSIVE jurisdiction of the Civil Courts of Barwani, Madhya Pradesh, India. No dispute shall be filed, heard, or adjudicated in any court outside the jurisdiction of Barwani, Madhya Pradesh. By using Yantra, you irrevocably and unconditionally submit to the exclusive personal jurisdiction of the courts located in Barwani, Madhya Pradesh, India, and you permanently waive any and all objections to the exercise of jurisdiction by such courts, any objection that such courts are an inconvenient forum, and any right to a jury trial.
16. Severability
If any provision of these Terms is found to be unenforceable or invalid under applicable law, that provision shall be modified to the minimum extent necessary to make it enforceable, or if it cannot be modified, it shall be severed from these Terms. The remainder of these Terms shall continue in full force and effect.
17. Entire Agreement
These Terms of Service, together with the EULA, Privacy Policy, Scientific Accuracy Disclaimer, and Minor User Policy contained in this document package, constitute the entire agreement between you and Yantra Labs with respect to your use of the application and supersede all prior and contemporaneous agreements, communications, and proposals, whether oral or written.
18. Contact
For any questions, concerns, or notices regarding these Terms of Service, please contact Yantra Labs at: legal@yantra.app
________________

DOCUMENT 2 — END USER LICENSE AGREEMENT (EULA)
Effective Date: 1 June 2026

THIS END USER LICENSE AGREEMENT IS A LEGAL AGREEMENT BETWEEN YOU AND YANTRA LABS. BY INSTALLING OR USING YANTRA, YOU AGREE TO BE BOUND BY THIS EULA. IF YOU DO NOT AGREE, DO NOT INSTALL OR USE THE APPLICATION.

1. Grant of License
Yantra Labs grants you a personal, non-exclusive, non-transferable, revocable license to use the Yantra application on a single Android device. This license is granted solely for your personal, non-commercial, educational use.
2. License Restrictions
You are expressly prohibited from:
* Copying or distributing the application or any portion of it
* Selling, renting, leasing, or sublicensing the application
* Reverse engineering, decompiling, disassembling, or attempting to derive the source code of the application
* Modifying, adapting, or creating derivative works from the application
* Removing, altering, or obscuring any copyright, trademark, or other proprietary notices
* Using the application for commercial purposes of any kind
* Circumventing or attempting to circumvent any technical protection measures in the application
* Using automated means to access or interact with the application
3. Ownership
Yantra Labs retains all right, title, and interest in and to the Yantra application, including all intellectual property rights therein. This EULA grants you a license to use the application — it does not transfer ownership of any kind. All rights not expressly granted in this EULA are reserved by Yantra Labs.
4. Updates and Modifications
Yantra Labs may from time to time release updates, patches, or new versions of the application. This EULA applies to all versions of the application. Updates may be required for continued use of certain features. Yantra Labs reserves the right to modify, suspend, or discontinue any feature or the entire application at any time without notice and without liability.
5. Third Party Components
The Yantra application may include open-source software components licensed under various open-source licenses. These components retain their original licenses. A list of third-party components and their licenses is available within the application. Your use of these components is governed by their respective licenses in addition to this EULA.
6. Experiment Content
The experiment instructions, calculation methods, report templates, and all other educational content within the application are original works of Yantra Labs and are protected by copyright. You may use this content only within the application for the purposes described in the Terms of Service. You may not copy, reproduce, or distribute this content outside the application.
7. Lab Reports
Lab reports generated by Yantra are documents created from your experimental data. The data in the reports is yours. The format, template, structure, and automatically generated text (precautions, sources of error, procedure) are the intellectual property of Yantra Labs. You may submit these reports to your school for educational purposes. You may not sell, distribute, or republish these reports commercially.
8. Termination
This EULA is effective until terminated. It terminates automatically and immediately if you fail to comply with any of its terms. Upon termination you must uninstall the application and destroy all copies. Sections 3, 9, and 10 of this EULA survive termination.
9. Disclaimer of Warranties
THE APPLICATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. YANTRA LABS MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
10. Limitation of Liability
YANTRA LABS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES RESULTING FROM YOUR USE OF OR INABILITY TO USE THE APPLICATION. YANTRA LABS'S TOTAL LIABILITY SHALL NOT EXCEED ZERO RUPEES (INR 0).
11. Governing Law
This EULA shall be governed by the laws of India. Disputes shall be resolved in the courts of Barwani, Madhya Pradesh, India.
________________

DOCUMENT 3 — PRIVACY POLICY
Effective Date: 1 June 2026

THE SHORT VERSION: Yantra collects almost no data. Everything stays on your device. Nothing is sent to our servers because we don't have a backend server. We do not collect, store, or sell your personal information.

1. Our Core Privacy Principle
Yantra is designed as an offline-first, locally-stored application. We built it this way deliberately. We do not want your data. We do not have the infrastructure to store your data. We do not benefit from collecting your data. This privacy policy exists to be transparent about the minimal data interactions that do occur.
2. Data Stored on Your Device
The following information is stored locally on your Android device, within the Yantra app's private storage, and is never transmitted anywhere:

Data Type
	Purpose
	Sent to Servers?
	Your name
	Displayed in app and printed on lab reports
	Never
	Class and board
	Filtering the experiment library to your curriculum
	Never
	School name
	Printed on lab reports
	Never
	Roll number (optional)
	Printed on lab reports if provided
	Never
	Subject selection
	Filtering the experiment library
	Never
	Sensor data from experiments
	Calculating results and generating reports
	Never
	Experiment results and history
	Progress tracking within the app
	Never
	Generated PDF reports
	Stored in your device's file system
	Never
	
3. Data We Do NOT Collect
To be absolutely explicit, Yantra does NOT collect:
* Your phone number or email address
* Your location or GPS coordinates
* Your device identifiers (IMEI, Android ID, advertising ID)
* Your usage behaviour, session length, or analytics data
* Crash reports or diagnostic data
* Camera images or microphone recordings beyond the immediate experiment session
* Contacts, files, or any other data from your device beyond what is listed in Section 2
* Any biometric data
* Payment information of any kind
4. Permissions Yantra Requests
Yantra requests the following Android permissions. Each permission is requested only when needed for a specific experiment and explained to you before the system dialog appears:

Permission
	Why It Is Needed
	RECORD_AUDIO
	Required for microphone-based experiments (sound frequency, speed of sound, resonance). Audio is processed in real-time and immediately discarded. No audio is saved to any file.
	CAMERA
	Required for camera-based experiments (projectile motion, heart rate, optics). Video and images are processed in real-time and never saved to your gallery or any file.
	ACCESS_FINE_LOCATION
	Required only for GPS-based experiments (speed measurement, stair-climbing power). Location data is used only for the duration of the experiment and immediately discarded.
	WRITE_EXTERNAL_STORAGE (Android 8 only)
	Required on Android 8 only to save PDF lab reports to your device storage. On Android 9 and above, reports are saved using the MediaStore API which does not require this permission.
	
5. No Backend, No Server, No Cloud
Yantra does not have a backend server. We do not operate any cloud infrastructure that stores user data. There is no database of Yantra users anywhere. When you delete the app, all your data is gone — there is no cloud backup, no server copy, and nothing for us to delete because we never had it.
6. Third Party SDKs and Libraries
The Yantra application uses certain open-source libraries to function (such as iText7 for PDF generation and sensor processing libraries). None of these libraries have been granted access to transmit user data externally. All third-party code used in Yantra operates entirely on-device.

Yantra does NOT include: advertising SDKs, analytics SDKs (Google Analytics, Firebase Analytics, etc.), crash reporting SDKs (Crashlytics, Sentry, etc.), social media SDKs, or any third party SDK that transmits data off-device.
7. Children's Privacy
Yantra is designed for use by students aged approximately 14 to 18. We take the privacy of minors seriously. Because we collect no personal data and maintain no user accounts, there is no personal information about minors stored on our servers (or anyone's servers). The only data about a minor user exists locally on the device they are using.

Parents and guardians should be aware that any lab reports generated by the application and shared by the student (for example, via WhatsApp to a teacher) will be subject to the privacy policies of those third-party platforms.
8. Data Security
Since all data is stored locally on your device, the security of your Yantra data is dependent on the security of your device. We recommend using a screen lock on your device. Yantra itself does not implement additional encryption beyond what Android provides for app-private storage.
9. Data Export Responsibility
DATA EXPORT: All generated PDFs and experimental data are stored locally on the device. Data only leaves the device when explicitly exported by the user (e.g., sharing a PDF via third-party applications like WhatsApp or Google Drive). Yantra Labs has no control over, and assumes no responsibility for, data once the user exports it to third-party services.
Since all your data is on your device, you have complete and total control over it:
* Access: Open the app and view your data at any time
* Delete: Uninstall the app to delete all Yantra data from your device
* Export: Generate PDF reports to export your experimental data
* Correction: Edit your profile details within the app at any time

There is no request process for exercising these rights because there is no remote data to request. Everything is in your hands, literally.
10. Changes to This Policy
If we ever change this Privacy Policy — for example if we add features that require data collection — we will update this document, change the effective date, and notify you within the app before any change takes effect. We will never collect data without informing you first.
11. Contact
For privacy-related questions: legal@yantra.app
________________

DOCUMENT 4 — SCIENTIFIC ACCURACY DISCLAIMER
Effective Date: 1 June 2026

1. Nature of Phone Sensor Data
Yantra uses the built-in sensors of consumer Android smartphones to collect experimental data. These sensors — accelerometers, gyroscopes, magnetometers, microphones, cameras, GPS receivers, and light sensors — are manufactured for general consumer use. They are not calibrated scientific instruments. They are not subject to metrology standards. Their accuracy, precision, and reliability vary significantly between devices, manufacturers, hardware generations, and individual units.
2. Known Sources of Error
Data collected through Yantra experiments is subject to the following known sources of error. This list is not exhaustive:
* Sensor manufacturing tolerance: variation between individual sensor units of the same model
* Temperature sensitivity: sensor readings shift with device temperature
* Magnetic interference: the phone's own electronic components interfere with magnetometer readings
* Vibration noise: ambient vibration contaminates accelerometer and gyroscope data
* Sampling rate limitations: consumer sensors sample at fixed rates that may not capture fast-changing phenomena accurately
* Quantisation error: digital sensors have finite resolution
* User technique variation: how the student performs the physical experiment affects results
* Environmental factors: humidity, air pressure, electromagnetic interference, and ambient light affect various sensors
* Physical setup imprecision: measurements of lengths, heights, and distances made by the student introduce additional error
* Filtering artefacts: the digital filters applied to raw sensor data to reduce noise may introduce phase lag or smooth out real phenomena
3. What the Results Are Good For
Despite the above limitations, Yantra experimental results are genuinely useful for:
* Understanding scientific concepts through personal, hands-on experience
* Learning experimental methodology — hypothesis, setup, data collection, analysis, conclusion
* Producing results in the correct order of magnitude for standard physical constants
* Observing qualitative relationships between variables (e.g., that longer pendulums have longer periods)
* Generating authentic, data-backed practical files for school submission
* Developing intuition for measurement error and its sources
4. What the Results Are Not Good For
ACADEMIC USE DISCLAIMER: While Yantra formats data to CBSE standards, Yantra Labs makes no guarantees regarding the acceptance of these reports by individual teachers, schools, or examination boards. Yantra Labs holds no liability for academic grading outcomes, rejected submissions, or disciplinary actions taken by educational institutions.
Yantra results must not be used for:
* Any engineering or structural calculation
* Any medical assessment, diagnosis, or health decision
* Any legal, regulatory, or compliance submission
* Any scientific publication or research without independent verification by calibrated instruments
* Any financial, insurance, or liability determination
* Any safety-critical assessment or decision

THE DATA PRODUCED BY YANTRA IS FOR EDUCATIONAL PURPOSES ONLY. ANY USE OF YANTRA DATA OUTSIDE OF PERSONAL EDUCATIONAL LEARNING IS ENTIRELY AT YOUR OWN RISK AND YANTRA LABS ACCEPTS NO LIABILITY WHATSOEVER FOR THE CONSEQUENCES OF SUCH USE.
5. Percentage Error and Standard Values
Where Yantra displays a percentage error by comparing your result to a standard value, this comparison is provided as an educational tool to help you understand the concept of experimental error. The standard values used are accepted scientific constants. The percentage error is a measure of how close your phone's sensors came to the accepted value — it is not a quality score or a pass/fail indicator.

A percentage error of 5-15% is typical and acceptable for the class of instrument being used. A very low percentage error does not mean your data is more accurate — it may mean your particular sensor unit happens to be well-calibrated, or that random errors cancelled out. A higher percentage error is a learning opportunity to identify sources of error, not a failure.
6. Heart Rate Measurements
The heart rate measurement experiment uses photoplethysmography (PPG) — the detection of blood flow through the finger using the phone camera and flash. This technique is used in commercial fitness wearables but in those devices is implemented with dedicated optical hardware and algorithms.

Yantra's implementation using a standard phone camera is less accurate than dedicated medical devices. The heart rate values produced by Yantra's heart rate experiment are approximate and should be treated as educational demonstrations of the PPG principle. They must not be used for medical assessment of any kind. If you have any concern about your cardiovascular health, consult a qualified medical professional.
________________

DOCUMENT 5 — MINOR USER POLICY
Effective Date: 1 June 2026

1. Who This Policy Covers
This policy applies to any user of Yantra who is under 18 years of age at the time of use, in accordance with the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 of India.
2. Parental Consent Requirement
Yantra is designed for secondary school students and the typical user will be between 14 and 18 years of age. Indian law and our own commitment to responsible development require that:
* Users under 18 must have the permission of a parent or legal guardian to use Yantra
* A parent or legal guardian of a minor user must read and accept these Terms of Service, the EULA, and this Minor User Policy on the minor's behalf before the minor uses the application
* By allowing a minor to use Yantra, the parent or guardian confirms that they have read all applicable documents and accept responsibility for the minor's use of the application
3. Parental Responsibilities
Parents and guardians who permit their child to use Yantra agree to:
* Supervise their child's use of the application, particularly during experiments that involve physical activity such as the free fall experiment
* Ensure their child understands that experimental data generated by Yantra is for educational purposes only
* Ensure their child understands that lab reports generated by Yantra must represent experiments they actually performed
* Review and understand what permissions the application requests and why
* Ensure the device used to run Yantra is in good physical condition and suitable for use in science experiments
4. Physical Safety for Minor Users
Parents and guardians should be aware that certain Yantra experiments require physical activity that carries a small risk of injury or device damage. Specifically:
* The free fall experiment requires dropping the phone onto a cushion — ensure adequate padding is used and the phone is not dropped from excessive heights
* The inclined plane experiment requires tilting a surface — ensure the student works on a stable surface and the phone cannot slide or fall
* The projectile motion experiment involves tracking a thrown object — ensure the student is in a safe, open space

All experiments include explicit safety instructions within the application. Parents and guardians are encouraged to review these instructions with their child before the child performs any experiment.
5. Content Appropriateness
All content within Yantra — experiment instructions, explanations, and generated reports — is appropriate for secondary school students and has been written for clarity and educational value. Yantra contains no advertising, no social interaction features, no user-generated content, and no content that is inappropriate for the intended age group.
6. Data and Privacy for Minors
As described in the Privacy Policy, Yantra collects no personal data and maintains no server-side records. The only information stored is what the student enters during onboarding (name, class, school) and the experimental data they generate — all stored locally on the device. Parents can review all data stored by Yantra by accessing the application on their child's device at any time. All data can be deleted by uninstalling the application.
7. Responsibility Allocation
When a minor uses Yantra:
* The parent or guardian is responsible for ensuring the minor understands and complies with all applicable terms
* The minor is responsible for performing experiments honestly and submitting only authentic lab reports to their school
* The school and teacher are responsible for supervising practical work in accordance with their own institutional policies
* Yantra Labs is responsible for providing accurate educational content, correctly processing sensor data, and generating properly formatted reports — and for nothing beyond this

________________

ACKNOWLEDGEMENT OF LEGAL DOCUMENTS

By using the Yantra application, you acknowledge that you have read, understood, and agree to be bound by:

6. Terms of Service
7. End User License Agreement (EULA)
8. Privacy Policy
9. Scientific Accuracy Disclaimer
10. Minor User Policy (if applicable)

You acknowledge that your use of the Yantra application constitutes your electronic acceptance of all of the above documents and that this acceptance is legally binding to the fullest extent permitted by applicable law.
"""
